[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30

[[services]]
name = "video-reframer"
source = "."

[services.video-reframer]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30
variables = { PORT = "8080" }